### ISSUE TITLE
Loading CW Data sometimes fails due to string length

### ISSUE THREAD

**Issue by waslem** [KelvinTegelaar/PowerShellWarrantyReports#1]
Thanks for the script.

I ran into the issue with invoke-restmethod for the ConnectWise API call in that it couldn't parse the JSON response due to the length, 

This workaround fixed it https://gist.github.com/smarkwell/60159fb1f56498f9a53d or just reducing the page size of the API call.

**Comment by KelvinTegelaar** [comment]
Will fix, thanks. :)

**Comment by KelvinTegelaar** [comment]
Resolved by decreasing page size to advised 250 items by CW API documentation.

**Comment by waslem** [comment]
Awesome, thanks!
