### ISSUE TITLE
Fujitsu Support?

### ISSUE THREAD

**Issue by ah-uk** [KelvinTegelaar/PowerShellWarrantyReports#13]
Wondering if it is possible to add support for this OEM at all please?

No API that I know of but some someone has already managed to do something similar so may be easy to add if you have a look here

https://blog.wydler.eu/2016/09/13/fujitsu-servicestatus-ueberpruefen/

**Comment by KelvinTegelaar** [comment]
Not going to support Fujitsu, sorry.
