### ISSUE TITLE
Export to CSV, or ability to filter asset types

### ISSUE THREAD

**Issue by dveldkamp** [KelvinTegelaar/PowerShellWarrantyReports#16]
Not really an issue per se, more of a feature request - it would be nice if there was an option to export reports to CSV, or if it was possible to filter asset types out of the report, to clean it up and only display device types that it's possible to pull warranty info on.

**Comment by KelvinTegelaar** [comment]
Added CSV exports to regular export functionality, both HTML and CSV files will be available.
