### ISSUE TITLE
Missing data only

### ISSUE THREAD

**Issue by netmc** [KelvinTegelaar/PowerShellWarrantyReports#17]
When using a PSA/RMM as the source, can this be set to only pull data for devices missing warranty information? Warranty information generally doesn't change, so very rarely would we need to repopulate data that is already present. It's also a bit nicer to the various vendor APIs.

**Comment by KelvinTegelaar** [comment]
I did that in the start, but found that a lot of people tend to increase warranties near their expire date or for example a carepaq or warranty extension is done at a later stage.

I'd love to find a workaround for that somehow, but haven't invested time into it. :)

**Comment by netmc** [comment]
That would work for my needs.  As far as working around for those that do warranty extensions, maybe have an option to check the warranty info if the current info shows expired or within X days of expiring? Maybe a "-IncludeExpired" switch? I don't think there is any sort of magic bullet unfortunately. For the most part, I would run the -MissingOnly switch, but probably once a month I would refresh everything. -MissingOnly - Daily; -IncludeExpired - Weekly; and a full refresh - Monthly.  With many of the APIs I use having daily use limits and rate limits, I try to be frugal with their use where I can.

**Comment by MichaelMcCool** [comment]
I'm using the module for the first time today, and have used it with the -missingonly switch. According to the verbose data, the command is making queries for each and every device irrespective if the warranty information is missing or not.

**Comment by netmc** [comment]
FYI, the -missingonly switch is supported for DattoRMM as that is the platform I use (and I made a pull request to implement it), but unsure if it is functional for other platforms.
