### ISSUE TITLE
HP Warranty and Syncro?

### ISSUE THREAD

**Issue by hennning** [KelvinTegelaar/PowerShellWarrantyReports#18]
Hi,
I'm using a version of your script right now in Syncro but we're really suffering from the HP Api problem.
Any ETA on when we can have that working again?

I also saw you plan to add native support for Syncro MSP, I'd really love that.
Happy to help you test it or troubleshoot anything.

**Comment by tmjwid** [comment]
HP api is on HP's end, no eta available from HP so nothing can be done I'm afraid, we're at the mercy of the vendors.

**Comment by hennning** [comment]
Ok, thank you.
