### ISSUE TITLE
Lenovo api auth failure

### ISSUE THREAD

**Issue by tmjwid** [KelvinTegelaar/PowerShellWarrantyReports#19]
Is the Lenovo iBase api failing to authenticate for anyone else? It has been failing for three days now.

**Comment by Brendan-Tengin** [comment]
Just found \ testing the script for the first time today. 
Found the same. I'm getting "No authorization to access Ibase." back from the API call.

Hopefully Lenovo haven't decided to lock it up! 
Might have to use https://supportapi.lenovo.com/Documentation/Warranty.html

**Comment by tmjwid** [comment]
I thought I had let another comment, but seems like I forgot to. 
We contacted our Lenovo rep, who confirmed that the LSC3/IBA4LSC3 username and password has been revoked. 
They recommend switching to the v2.5, which we will be in our application, but just wanted to let you know as well. 
Users will now need to request an api token from Lenovo, which is alot easier said than done. You "need" an account manager for a start, which I think for Lenovo means you need alot of their machines. It's a right chore.

**Comment by KelvinTegelaar** [comment]
Working on this with our Lenovo rep.

**Comment by tmjwid** [comment]
Just a heads up, in case you have to switch to the v2.5 api. https://github.com/Protirus/PoshLenovo
A very good implementation of the api in powershell.

**Comment by KelvinTegelaar** [comment]
Changed API to Azure Function that will support queries to lenovo API without API key. Azure function is still in development so not  pushing to gallery yet.

**Comment by KelvinTegelaar** [comment]
(This does mean you can run from source for Lenovo. Expect push to PSGallery after this weekend.
