### ISSUE TITLE
HP error

### ISSUE THREAD

**Issue by jangshant** [KelvinTegelaar/PowerShellWarrantyReports#2]
Getting this error any idea?

----------------------------------------------------------------------------------------------------------------------------------------------
Invoke-RestMethod : The remote server returned an error: (500) Internal Server Error.
At C:\Users\jangshant.singh\Desktop\Warranty\WarrantyRetrieval-new.ps1:30 char:14
+ ...    $HPReq = Invoke-RestMethod -Uri "https://support.hp.com/hp-pps-ser ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by KelvinTegelaar** [comment]
Unfortunately, we've seen this multiple times in the last couple of weeks. The HP API is going down, requesting Captcha's or just not returning results at all. Its a matter of waiting for them to fix it.
