### ISSUE TITLE
Set-WarrantyAPIKeys doesn't ask me for the DellClientSecret.

### ISSUE THREAD

**Issue by jus32111** [KelvinTegelaar/PowerShellWarrantyReports#23]
I've got the same problem, unfortunatly reinstalling it and trying it on a different machine does not work for me.
Set-warrantyAPIKeys only asks me for the DellClientID and seems to skip the DellClientSecret.

Causing Get-DellWarranty.ps1 to give me the folowing error:

Source is Datto RMM. Grabbing all devices.
Getting DattoRMM Devices
Invoke-RESTMethod : {
  "error":"invalid_client",
  "error_description":"The given client credentials were not valid"
}
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.2.1\private\Get-DellWarranty.ps1:22 char:23
+ ... uthResult = Invoke-RESTMethod -Method Post -Uri $AuthURI -Body $AuthB ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : {

      "Fault": {
         "faultcode": "401",
         "faultstring": "Invalid Authentication",
         "faultactor": "https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements?servicetags=XXXX"
      }

}

_Originally posted by @jus32111 in https://github.com/KelvinTegelaar/PowerShellWarrantyReports/issues/20#issuecomment-776788197_

**Comment by KelvinTegelaar** [comment]
It seems like I did not make both parameters mandatory, workaround:
`Set-WarrantyAPIKeys -DellClientID 'YOURID' -DellClientSecret 'YOURSECRET'

Fixed in latest build, so closed for now.

**Comment by jus32111** [comment]
Thanks!
That works.
