### ISSUE TITLE
HP Warranty API

### ISSUE THREAD

**Issue by BasicWombat** [KelvinTegelaar/PowerShellWarrantyReports#37]
I'm no expert by any means, but I have found this site about the HP Warranty API.
Does this help in getting this update for this script?

https://developers.hp.com/css/doc/product-warranty-api-scripts

**Comment by tmjwid** [comment]
This api is down, it says so at the start in big red text but if this api is every brought back by HP, then I imagine it'll be the one used.

**Comment by aescolastico** [comment]
@KelvinTegelaar Can we get an "-ExcludeHP" parameter in the mean time?
