### ISSUE TITLE
HP warranty API

### ISSUE THREAD

**Issue by remyborde** [KelvinTegelaar/PowerShellWarrantyReports#4]
Possible to update your great script with HP API

Thx

**Comment by KelvinTegelaar** [comment]
HPs warranty APIs have been taken offline. HP is working on a new API for somewhere in 2020

**Comment by remyborde** [comment]
So for moment we don't have any solution for check warranty with HP ? 
thanks for your quick answer :)

**Comment by KelvinTegelaar** [comment]
Correct.
