### ISSUE TITLE
HP Warranty hidden recaptcha blocking lookups

### ISSUE THREAD

**Issue by rjodwyer** [KelvinTegelaar/PowerShellWarrantyReports#40]
Hi,

Just found this recently, and thought I could use it to link ITGlue.

Seems the HP warranty page now has a hidden recaptcha that seems to stop it working.

Keep getting access denied when I extrapolated the commands into Powershell.

Then I could copy the powershell command from Chrome which progressed past the access denied, but then hits the recaptcha fail.

Is it just me with this issue?

thanks,
Ryan

**Comment by staze** [comment]
Seeing same thing. =/ Was trying to figure out what was going on, but this seems to be what I'm seeing. 

Bummer they keep shutting off these abilities. =(

**Comment by KelvinTegelaar** [comment]
fixed

**Comment by staze** [comment]
Can confirm! 

*starts timer until HP breaks it again*

**Comment by staze** [comment]
it works! now we wait until HP breaks it again...

**Comment by tmjwid** [comment]
Do you have any released sources on how you access the HP api correctly? I can't really use a proxy for our application.

**Comment by KelvinTegelaar** [comment]
@tmjwid  see the readme, vendors or users that want to use the warranty lookups in their applications can either sponsor me, or pay for the proxies.

**Comment by tmjwid** [comment]
Oh yes I see, thank you.
