### ISSUE TITLE
Warranty Proxy App down

### ISSUE THREAD

**Issue by aescolastico** [KelvinTegelaar/PowerShellWarrantyReports#44]
I'm receiving 403 errors when checking for Lenovo devices:
`Invoke-RestMethod: /Users/Andy/.local/share/powershell/Modules/PSWarranty/private/Get-LenovoWarranty.ps1:4 
Line |                                                                                                     
   4 |      $Req = Invoke-RestMethod -Uri $APIURL -Method get                                              
     |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                              
     |        Web App - Unavailable              html {             height: 100%;                          
     | width: 100%;         }          #feature {             width: 960px;                                
     | margin: 95px auto 0 auto;             overflow: auto;         }          #content {                 
     | font-family: "Segoe UI";             font-weight: normal;             font-size: 22px;              
     | color: #ffffff;             float: left;             width: 460px;                                  
     | margin-top: 68px;             margin-left: 0px;             vertical-align: middle;                 
     | }              #content h1 {                 font-family: "Segoe UI Light";                         
     | color: #ffffff;                 font-weight: normal;                 font-size: 60px;               
     | line-height: 48pt;                 width: 800px;             }          p a, p                      
     | a:visited, p a:active, p a:hover {             color: #ffffff;         }                            
     | #content a.button {             background: #0DBCF2;             border: 1px solid                  
     | #FFFFFF;             color: #FFFFFF;             display: inline-block;                             
     | font-family: Segoe UI;             font-size: 24px;             line-height: 46px;                  
     | margin-top: 10px;             padding: 0 15px 3px;             text-decoration: none;               
     | }              #content a.button img {                 float: right;                                
     | padding: 10px 0 0 15px;             }              #content a.button:hover {                        
     | background: #1C75BC;             }                                          Error                   
     | 403 - This web app is stopped.                 The web app you have attempted to reach              
     | is currently stopped and does not accept any requests. Please try to reload the page or             
     | visit it again soon.                 If you are the web app administrator, please find              
     | the common 403 error scenarios and resolution here. For further troubleshooting tools and           
     | recommendations, please visit Azure Portal.                                                         
`
<img width="749" alt="image" src="https://user-images.githubusercontent.com/30540257/151085300-f01544fb-afed-4338-b48e-9149283cbe36.png">

**Comment by dlmerdian** [comment]
I can second this one.  It looks like Lenovo may have moved to a new API url.
"https://csp.lenovo.com/ibapp/il/WarrantyStatus.jsp?serial="
Unfortunately, this one doesn't appear to populate the Start Date.

**Comment by KelvinTegelaar** [comment]
The warranty api proxy is temporarily offline due to abuse. Will be back soon :)
