### ISSUE TITLE
Lenovo warranty lookup failing 

### ISSUE THREAD

**Issue by simonoid-iit** [KelvinTegelaar/PowerShellWarrantyReports#47]
Looks like the Azure app for Lenovo lookups has stopped. When running I get this error message:

> 
> Error 403 - This web app is stopped.
>                 The web app you have attempted to reach is currently stopped and does not accept any requests. Please
> try to reload the page or visit it again soon.
>                 If you are the web app administrator, please find the common 403 error scenarios and resolution here.
> For further troubleshooting tools and recommendations, please visit Azure Portal.

**Comment by simonoid-iit** [comment]
Oh I see that this has been update in the blog post 

> [Kelvin Tegelaar](http://www.cyberdrain.com/)
> February 20, 2022 at 11:42 am
> 
> Yeah, I took it down for a bit due to abuse. will be back sometime soon.

**Comment by KelvinTegelaar** [comment]
Its back up :)
