### ISSUE TITLE
Dell Warranty API includes non-warranty related items

### ISSUE THREAD

**Issue by chrisjantzen** [KelvinTegelaar/PowerShellWarrantyReports#48]
I have been using this module for a bit now and we recently noticed that some of our devices had the wrong warranty date set. When looking into this, I found that the warranty had expired but there was another service that went beyond the warranty. In our case these were things like "Dell Digital Delivery". Looking into this further, it appears the Dell API returns more than just warranty info.

Here is an example of the issue:
![image](https://user-images.githubusercontent.com/22362786/163053529-0f1c2f0c-982e-4cef-8fa4-3fe2babd00e9.png)

With the Dell API, each service is broken down into a Service Level Code, Description, and Group. I was hoping that certain groups would include warranty info so I contacted Dell and got ahold of their API team. Unfortunately, it does not seem like we can simply filter based on group and their tech said there are thousands of different service level codes so it wouldn't be simple to go through them all to determine which are not warranty related. 

Anyways, I generated a list of codes for all of our Dell devices (~3000) and sent this to their technician, he was able to tell me which of them were not warranty related. 

I have modified the Get-DellWarranty function to include a blacklist of Service Level Codes and included the 4 codes that were causing a problem for us. I suspect there are more codes that will be an issue for other people, but it seems like they'll need to be added on a case-by-case basis.

These are the codes that I have currently blacklisted based on their suggestions:
- D = Dell Digital Delivery
- DL = Dell
- PJ = ProDeploy Basic
- PR = Depot, Customer Paid Freight

The array uses the Service Level Codes (e.g. DL).

I have also created a script you can use to easily get a list of all the Dell Service Codes related to your devices, I'll post that here as well. If anyone else is having issues, you may want to grab a list and send it off to Dell to find more codes to blacklist. The script is targeted at Autotask but could easily be modified to use a different PSA or RMM. Just run it and you'll get a GridView when it completes with a list of all the Service Codes and their Descriptions. Dell's API team can be contacted at "APIs_TechDirect@Dell.com" if you want them to review your list of codes.

**Comment by chrisjantzen** [comment]
The following script can be used to pull a list of all the Dell Service codes related to your Dell Devices. Just fill in the DellAPI and AutotaskAPI info. 

If you want to pull computers from somewhere other than Autotask it should be fairly easy to modify, the script is simply pulling a list of all active devices into the variable `$AllDevices` and then using the `.serialNumber` on each device. Just modify it to pull a list of all devices from a different API into `$AllDevices` and then modify the 2 instances of `$Device.serialNumber` to match the serial number property, if required.

```powershell
$DellAPI = @{
	ID = ""
	Secret = ""
}

$AutotaskAPI = @{
	Url = "https://webservicesXX.autotask.net/atservicesrest"
	Username = ""
	Key = ''
	IntegrationCode = ""
}

Import-Module AutotaskAPI
$AutotaskPassword = ConvertTo-SecureString $AutotaskAPI.Key -AsPlainText -Force
$AutotaskCreds = New-Object System.Management.Automation.PSCredential -ArgumentList ($AutotaskAPI.Username, $AutotaskPassword)
Add-AutotaskAPIAuth -ApiIntegrationcode $AutotaskAPI.IntegrationCode -credentials $AutotaskCreds
Add-AutotaskBaseURI -BaseURI $AutotaskAPI.Url

$Filters = @(
	@{
		op = "eq"
		field = "isActive"
		value = "True"
	}
)
$DeviceFilter = @{
	filter = @(
		$Filters
	)
} | ConvertTo-Json -Depth 10 -Compress

$AllDevices = Get-AutotaskAPIResource -Resource ConfigurationItems -SearchQuery $DeviceFilter
$DeviceCount = ($AllDevices | Measure-Object).Count
$WarrantyProducts = [System.Collections.ArrayList]@()
$i = 0
foreach ($Device in $AllDevices) {
	$i++
	$PercentComplete = $i / $DeviceCount * 100
	Write-Progress -Activity "Getting Warranty Info" -Status "$PercentComplete% Complete: $i / $DeviceCount" -PercentComplete $PercentComplete
	if ($Device.serialNumber.Length -eq 7) {
		$AuthURI = "https://apigtwb2c.us.dell.com/auth/oauth/v2/token"
		if ($TokenAge -lt (get-date).AddMinutes(-55)) { $Token = $null }
		If ($null -eq $Token) {
			$OAuth = "$($DellAPI.ID)`:$($DellAPI.Secret)"
			$Bytes = [System.Text.Encoding]::ASCII.GetBytes($OAuth)
			$EncodedOAuth = [Convert]::ToBase64String($Bytes)
			$headersAuth = @{ "authorization" = "Basic $EncodedOAuth" }
			$Authbody = 'grant_type=client_credentials'
			$AuthResult = Invoke-RESTMethod -Method Post -Uri $AuthURI -Body $AuthBody -Headers $HeadersAuth
			$token = $AuthResult.access_token
			$TokenAge = (get-date)
		}

		$headersReq = @{ "Authorization" = "Bearer $Token" }
		$ReqBody = @{ servicetags = $Device.serialNumber }
		$WarReq = Invoke-RestMethod -Uri "https://apigtwb2c.us.dell.com/PROD/sbil/eapi/v5/asset-entitlements" -Headers $headersReq -Body $ReqBody -Method Get -ContentType "application/json"
		$Products = $warreq.entitlements

		foreach ($Product in $Products) {
			if ($WarrantyProducts.ServiceLevelDescription -like $Product.serviceLevelDescription) {
				continue;
			}
			$WarrantyProducts.Add([PSCustomObject]@{
				ServiceLevelCode = $Product.serviceLevelCode
				ServiceLevelDescription = $Product.serviceLevelDescription
				ServiceLevelGroup = $Product.serviceLevelGroup
			});
		}
	}
}

$WarrantyProducts | Sort-Object ServiceLevelDescription | Out-GridView 

```

**Comment by KelvinTegelaar** [comment]
merged
