### ISSUE TITLE
How does the CSV need to be formatted? 

### ISSUE THREAD

**Issue by ali3nz** [KelvinTegelaar/PowerShellWarrantyReports#50]
Im sorry but I can't find this information anywhere. No report is being generated when running against source CSV at present. 

Potentially this is due to the source CSV being formatted incorrectly.

**Comment by KelvinTegelaar** [comment]
With the updats to my blog it seems that has gone away, you'll need these fields:
vendor, serialNumber, client

**Comment by ali3nz** [comment]
Thank you so much Kevin. You have put a lot of work in this script even going so far to make it auto sync with MSP tools rather then just generating an HTML report. Impressive work and I'm very grateful. Thanks for responding to me as well.
