### ISSUE TITLE
HP Warranty requiring SKU/Product Number

### ISSUE THREAD

**Issue by skoliver1** [KelvinTegelaar/PowerShellWarrantyReports#52]
First off, THANK YOU for all your hard work in putting this together!  It's been working wonderfully for almost all my clients.

However, I am seeing some HP serial numbers that don't work because HP requires the SKU/Product number to fully look up the warranty information.

Example:
s/n: CND1111P7B
Product Number: 36D38UT

When passing the serial number to the website, it gives:
{
  "Serial": "CND1111P7B",
  "WarProduct": "",
  "StartDate": null,
  "EndDate": null
}

In the script, this results in this error:
```Powershell
Cannot convert null to type "System.DateTime".
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.7.1\private\Get-HPWarranty.ps1:12 char:30
+ ...      $WarrantyState = if ([DateTime]$HPReq.endDate -le $today) { "Exp ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast

Cannot convert null to type "System.DateTime".
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.7.1\private\Get-HPWarranty.ps1:13 char:9
+         $WarObj = [PSCustomObject]@{
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast
```

I did some minor testing with the URL:
https://warrantyapiproxy.azurewebsites.net/api/HP?serial=CND1111P7B&productnumber=36D38UT
https://warrantyapiproxy.azurewebsites.net/api/HP?serial=CND1111P7B&product=36D38UT
https://warrantyapiproxy.azurewebsites.net/api/HP?serial=CND1111P7B&sku=36D38UT

But could not get this to give additional information.  Is this additional information possible to send through the API?

**Comment by KelvinTegelaar** [comment]
No, you cannot ship productnumber via this API. Those serials can't be looked up via the module.
