### ISSUE TITLE
Cannot convert null to type "System.DateTime

### ISSUE THREAD

**Issue by Dmartin1005** [KelvinTegelaar/PowerShellWarrantyReports#53]
Importing from CSV. Getting Cannot convert null to type "System.DateTime

did more testing looks like random serial numbers return this result but don’t show on the report. Running same sn in hp support assistant or hp website show results

**Comment by slsconsult** [comment]
Same issue here, fe when I run the line https://warrantyapiproxy.azurewebsites.net/api/HP?serial=5CD201343S I got 

{
  "Serial": "5CD201343S",
  "WarProduct": "",
  "StartDate": null,
  "EndDate": null
}

**Comment by KelvinTegelaar** [comment]
Some devices that require a PN cannot be looked up.
