### ISSUE TITLE
Microsoft API Offline

### ISSUE THREAD

**Issue by schenardie** [KelvinTegelaar/PowerShellWarrantyReports#54]
Hi Kelvin, 
Just a heads up the web app for microsoft warranty was stopped
https://surfacewarrantyservice.azurewebsites.net/api/key

Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

Not sure how did you found the api or if you can find a new one but just though to raise this.

**Comment by schenardie** [comment]
Got as far as figuring that:
they changed the api to https://surfacedma.azurefd.net/api/warranty
they changed the body fields (serialnumber is not accepted anymore)
the response is encoded but i could not find the way of de-encoding it

Hope it helps

**Comment by shobhitvaish** [comment]
> 

Could you please help me with the new warranty endpoint where I need to post the request? Also, may I know how to create the body for the new endpoint? I can try decoding the response.

**Comment by KelvinTegelaar** [comment]
I am aware. Working with MS to get this back up somehow.

**Comment by staze** [comment]
@KelvinTegelaar Any update on this? Anything we can do to help?

**Comment by mr-childers** [comment]
Any updates?

**Comment by simonlindner** [comment]
Any updates?

**Comment by altjones** [comment]
Hi 
Love the work.
Like others I'd love to see MS warranty info working...
Any Updates to this?

**Comment by Abe-Telo** [comment]
#92 Microsoft might allow this now. Could you check what this means for us?

**Comment by staze** [comment]
Looks like they have rolled out an official API for this info: https://techcommunity.microsoft.com/blog/surfaceitpro/introducing-the-surface-api-management-service/4107282

**Comment by Abe-Telo** [comment]
Yes, However it sounds complicated to set up, I tried, it was very confusing. I did not get it working yet. If anyone does let us know how so i can replicate your instructions.

**Comment by staze** [comment]
I'm waiting for feedback from MS. Their entra app requirement is extremely vague/hand-waivey. "You need an app, here's a generic article". 

Once I hear back and get it going, will see if I can provide instructions. But yes, definitely not as simple as "here's an API secret/key" like Dell and Lenovo. 

Wonder if we'll ever see HP provide something like this again. lol.

**Comment by Abe-Telo** [comment]
Further investigation, Based on a phone conversation i had with MS, I understood the linked method above is intended for Clients/Companies that manage there own devices.  Meaning you will have to add your devices in Intune in order to get accesses to the API that may be restricted to your own company. The question is how accrete my info is, and if there is another way? I mean there are other companies that do have access and charge a lot of money to have access to there MS API.
