### ISSUE TITLE
Generic serial numbers misidentified/Wrong manufacturer queried

### ISSUE THREAD

**Issue by netmc** [KelvinTegelaar/PowerShellWarrantyReports#56]
Several motherboard vendors (white box) use a generic serial number of '1234567890' or variation thereof. These serial numbers are treated as an HP serial number currently which is definitely not the case. Similarly, it appears that the warranty API to use is based solely upon the serial number format instead of the device's audit information from the RMM which already contains the manufacturer information. Limiting the queries to only supported vendors would greatly speed up the time it takes to check warranty information. I understand that this may not be available in all use cases, but if the RMM provides it, leveraging this data makes sense.

Edit: It appears that while the vendor information is used, the fallback just looks at the serial number length, so these fake serial numbers are sent off to the HP provider.

**Comment by KelvinTegelaar** [comment]
Think we could make an explicit `-ManualVendorOnly` switch. Looking into this this month :)
