### ISSUE TITLE
No information on how to format input CSV file

### ISSUE THREAD

**Issue by TheStuffClicker** [KelvinTegelaar/PowerShellWarrantyReports#59]
Both site and Github page have no information on how to format the input CSV file - I tried a simple list of Service Tags in the first column of a CSV and it does not work. The HTML report generates like so -
![image](https://user-images.githubusercontent.com/117664929/200351174-460d0815-58cb-4b62-9285-ed16a040943a.png)

**Comment by MattTheEmp** [comment]
I am sure this is maybe no longer helpful to you but i will leave this here for future people needing help. 
Including myself when i forget i already solved this lol

the ps command will look like this 
`update-warrantyinfo -CSV -CSVFilePath "C:\Temp\maghp.csv" -GenerateReports -LogActions`

and the csv should look like this

serialnumber,client,vendor,
<S/N>,,HP,
<S/N>,,HP,
