### ISSUE TITLE
HP require Product numer for some products

### ISSUE THREAD

**Issue by UlfTallmyr-Atea** [KelvinTegelaar/PowerShellWarrantyReports#62]
Hi,
HP reuse the serial numbers for some products, and if you try to get the warranty info for one of those you will get the "Could not get warranty information" error.
Would it be possible to add the Product number as a search parameter? An example of this is 00354113612063478855.

**Comment by tehNiah** [comment]
Hope this gets fixed, it seems that a lot of new HP laptops require product number to check warranty

**Comment by brjo40** [comment]
If this is fixed then the data API would work fine, but without it it is unusable.

**Comment by UlfTallmyr-Atea** [comment]
Hi Kelvin,
I was going to try this out, but I can't see that the code has been updated. Is there anything I need to do to make it work?
