### ISSUE TITLE
Azure web app stopped

### ISSUE THREAD

**Issue by Natycat33** [KelvinTegelaar/PowerShellWarrantyReports#63]
The [Azure web app ](https://warrantyapiproxy.azurewebsites.net/)used to proxy the warranty API requests for HP and Lenovo is currently giving a 403 because the web app is stopped. Is this a mistake or is the service down indefinitely?

**Comment by petermikula** [comment]
@KelvinTegelaar  is it the same case with Microsoft Surface warranty API site? https://surfacewarrantyservice.azurewebsites.net/ Will that be back up anytime soon?

**Comment by Natycat33** [comment]
It looks like the web app is still down, I'm not even getting a 403 now. What's the current status on this?

**Comment by Natycat33** [comment]
Seems like this is fixed
