### ISSUE TITLE
Get-WarrantyITG - Unidentified serial numbers appear to use the previous lookup's expiration date

### ISSUE THREAD

**Issue by mattelliott89** [KelvinTegelaar/PowerShellWarrantyReports#7]
Hi Kelvin!

I am seeing incorrect expiration dates being populated for "unidentified" serial numbers, meaning anything not Dell, HP, Lenovo, or MS. Instead of just leaving those dates blank, it looks like it is using the object with whatever date it had previously pulled. I suspect this is due to the switch identifying serial numbers by length. I believe it may be able to be resolved by adding a Default clause to the switch to set the object to either null or it's existing value if it doesn't find a matching serial number length.

**Comment by KelvinTegelaar** [comment]
Solved with a default state! :)
