### ISSUE TITLE
HP Warranty not working anymore?

### ISSUE THREAD

**Issue by staze** [KelvinTegelaar/PowerShellWarrantyReports#72]
Hello there,

HP warranty lookup seems to have stopped working. I just get a "Invoke-RestMethod:  Received an unexpected EOF or 0 bytes from the transport stream."

Tried to be very easy on the API. Any hope this will come back online?

**Comment by KelvinTegelaar** [comment]
Nah, too many jokers making 1 billion requests. Not putting any more effort into this :)

**Comment by TechEnvyPtyLtd** [comment]
Would you consider allowing us to self host the HP Azure site or add a IP monthly limit?

**Comment by KelvinTegelaar** [comment]
Nope.

**Comment by TechEnvyPtyLtd** [comment]
lol ok!

**Comment by staze** [comment]
Hey @KelvinTegelaar That sucks. =( we made like, 10 requests a week. =/ Do you know of any alternatives? I'm not even sure HP ever finally released their "new" warranty API. =(

**Comment by wpltechstaff** [comment]
So there's no way to do this without the proxy at warrantyapiproxy.azurewebsites.net ?

**Comment by Alex-ll-2021** [comment]
Thanks for your effort. I understand the api been closed due to too many requests
```
While checking the tiny exe file from HPSA get confused of IISReport.PostIISLog() and + urlObj as string for the web request

What is the sting of urlObj ?, can you please give some advice? Thank you!
