### ISSUE TITLE
Internet Explorer Engine

### ISSUE THREAD

**Issue by Solar-Pete** [KelvinTegelaar/PowerShellWarrantyReports#76]
Hello! Long time lurker of yours, and full time enjoyer of your powershell scripts. I've just been looking into this for our Ninja setup, and when trying to run for the first time I get this error.

```
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete.
Specify the UseBasicParsing parameter and try again.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:18 char:15
+ ...   $Result = Invoke-WebRequest -uri "$($NinjaURL)/ws/oauth/token" -Met ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:21 char:56
+ ... uthorization' = "Bearer $(($Result.content | convertfrom-json).access ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Invoke-WebRequest : {"error":"invalid_header","error_description":"Invalid 'Authorization' header","error_code":1}
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:24 char:16
+ ...  $OrgsRaw = Invoke-WebRequest -uri "$($NinjaURL)/v2/organizations" -M ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:25 char:29
+     $NinjaOrgs = $OrgsRaw | ConvertFrom-Json
+                             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Invoke-WebRequest : {"error":"invalid_header","error_description":"Invalid 'Authorization' header","error_code":1}
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:33 char:23
+ ... evicesRaw = Invoke-WebRequest -uri "$($NinjaURL)/v2/devices-detailed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:34 char:42
+         $Devices = $DevicesRaw.content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

Now obviously, as IE is depreciated I'm sure it shouldn't be using it. Perhaps it's something on my side?

**Comment by Solar-Pete** [comment]
I have actually resolved this issue by editing the Ninja powershell in the module to use Invoke-RestMethod. Would like to help change other bits of the module if you'd like?

**Comment by jcrookwa** [comment]
@Solar-Pete I'm having the same issues with the below two lines. Would you care to share how you fixed it?

Invoke-RestMethod : { "resultCode": "FAILURE", "errorMessage": "IllegalStateException", "incidentId": 
"WEB_MGMT_SERVICE-2a-1689058699-DGMNFTSZ" }
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:33 char:24
+ ... vicesRaw =  Invoke-RestMethod -uri "$($NinjaURL)/v2/devices-detailed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:34 char:42
+         $Devices = $DevicesRaw.content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFrom 
   JsonCommand

**Comment by Solar-Pete** [comment]
So you have to get rid of the convertfrom-json as the invoke-restmethod gets it in the correct format currently. 

So the line with $Result needs to change to
`$Result = Invoke-RestMethod -uri "$($NinjaURL)/ws/oauth/token" -Method POST -Body $AuthBody -ContentType 'application/x-www-form-urlencoded'
$AuthHeader = @{
    'Authorization' = "Bearer $($Result.access_token)"
}
`

Change the $OrgsRaw line:
`
$NinjaOrgs = Invoke-RestMethod -uri "$($NinjaURL)/v2/organizations" -Method GET -Headers $AuthHeader
`

Edit the $DevicesRaw line inside the else clause:
`$Devices = Invoke-RestMethod -uri "$($NinjaURL)/v2/devices-detailed" -Method GET -Headers $AuthHeader`

In the part where you're making a GET request for the device fields, replace the Invoke-WebRequest:
`$DeviceFields = Invoke-RestMethod -uri "$($NinjaURL)/v2/device/$($Device.id)/custom-fields" -Method GET -Headers $AuthHeader
$WarrantyDate = $DeviceFields."$($NinjaFieldName)"
`

I've found that the Lenovo one isn't working any more due to the webapp being down. I'm working on looking into seeing if I can put my own up, will confirm if I get the chance to/figure out what the previous one did.
