### ISSUE TITLE
Invoke Web Request Errors

### ISSUE THREAD

**Issue by jcrookwa** [KelvinTegelaar/PowerShellWarrantyReports#77]
Hi there,

We're having issues with Ninja specifically with the below error:
Invoke-WebRequest : { "resultCode": "FAILURE", "errorMessage": "IllegalStateException", "incidentId": 
"WEB_MGMT_SERVICE-2a-1689058491-XMIKPVBV" }
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:33 char:23
+ ... evicesRaw = Invoke-WebRequest -uri "$($NinjaURL)/v2/devices-detailed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\private\Get-WarrantyNinja.ps1:34 char:42
+         $Devices = $DevicesRaw.content | ConvertFrom-Json
+                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFrom 
   JsonCommand
 

Is there a known work around for this?

**Comment by ktague25** [comment]
Hello, we ran into the same issue with Ninja. It looks like it's caused by mobile devices. Try removing any that you are testing and run the script again.
