### ISSUE TITLE
Could not get warranty information.

### ISSUE THREAD

**Issue by KleiDav** [KelvinTegelaar/PowerShellWarrantyReports#79]
Script running well, I can see it because it grabs all serials from our Autotask, and is able to get Apple warranties (even if estimates)
But for all other vendors I get "Could not get warranty information." without more informations, except for DELL machines where I get a "Could not get warranty information - No API key"
For DELL, truth is that I'm still waiting for DELL to send me the key, but for LENOVO (80% of our devices), should not need an API key?

Is the script still working?

![image](https://github.com/KelvinTegelaar/PowerShellWarrantyReports/assets/13157143/eb83408f-2f1c-4174-bccd-62dd127ca224)

**Comment by r0bot85** [comment]
Author updated the repo 5 days ago saying none are working except Dell at this time. So i guess that just confirms your issue.
