### ISSUE TITLE
Should this still be working with NinjaOne API? (getting "INVALID_ATTRIBUTE_VALUE"

### ISSUE THREAD

**Issue by cyanide699** [KelvinTegelaar/PowerShellWarrantyReports#82]
Hi, firstly many thanks for all your work!

I have got Ninja API (Client cred setup as per Lukes guide in https://mspp.io/ninjaone-pswarranty-support/ )
have got my Techdirect API keys and when running

using powershell 7.4.0

Set-WarrantyAPIKeys -DellClientID "x" -DellClientSecret "x"
update-warrantyinfo -Ninja -NinjaClientID "x" -NinjaSecret "x" -NinjaURL "https://eu.ninjarmm.com" -NinjaFieldName "warrantyexpiry" -SyncWithSource -OverwriteWarranty -ExcludeApple

I can see it scrolling through all the devices "Processing etc" 

but for each (and we have mostly 99% dell devices) get the error 
"INVALID_ATTRIBUTE_VALUE"

(the warrantyexpiry is a DATE field, with full Read/write for scripts & API - I have tried Global & role based custom field... same

114 |  … ntyStatus = Get-WarrantyNinja -NinjaURL $NinjaURL -Secretkey $NinjaSe …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to update device: TESTDEVICE  {   "resultCode": "FAILURE",   "errorMessage": "INVALID_ATTRIBUTE_VALUE",   "incidentId":

PS C:\Windows\System32> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32> Get-Module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     1.4.8.1               PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package,…
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Fin…
Script     2.3.4                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …
Script     1.8.0                 PSWarranty                          {Get-Warrantyinfo, Set-WarrantyAPIKeys, update-wa…

**Comment by cyanide699** [comment]
as a test ive set the date field (that was mentioned to use in the setup guide ) to a text field and it does work so both api's are working,  (however gives the date in epoch format e.g  1.636956E12

**Comment by annoyerjones** [comment]
I seem to have the same issue. I noticed it only effects new Dell Latitude 53xx series models. All others work fine. I don't know what has changed.

**Comment by EarnestFlowers** [comment]
yesterday 3/6/2024 .. some devices were erroring out and having the 1.xxxE for a date.

today .. there is no error but its still not processing the 1.xxxE for a date.

**Comment by EarnestFlowers** [comment]
yesterday 3/6/2024 .. some devices were erroring out and having the 1.xxxE for a date.

today .. there is no error but its still not processing the 1.xxxE for a date.

**Comment by BluebirdTechnology** [comment]
I am getting this error as well but it seems to only apply on any Dell machine that is still under warranty. It isn't indicating when it expires but the expired ones all work.

The error I get is:
Get-WarrantyNinja : Failed to update device: <PC NAME> { "resultCode": "FAILURE", "errorMessage":
"INVALID_ATTRIBUTE_VALUE", "incidentId": "WEB_MGMT_SERVICE-2a-<ID>" }
At C:\Program Files\WindowsPowerShell\Modules\PSWarranty\1.8.0\Public\Update-WarrantyInfo.ps1:114 char:35
+ ... ntyStatus = Get-WarrantyNinja -NinjaURL $NinjaURL -Secretkey $NinjaSe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-WarrantyNinja
