### ISSUE TITLE
Permanently add Dell API key

### ISSUE THREAD

**Issue by aK1NG40K** [KelvinTegelaar/PowerShellWarrantyReports#83]
Is there a way to permanently add the Dell API key/secret to the script without having to use Set-WarrantyAPIKeys each time PS is started?

We're using the following script (https://github.com/snipe/snipe-it/issues/7326#issuecomment-1271112555) to import warranty info into Snipe-IT and would like to schedule it to run automatically.

**Comment by ronmanp** [comment]
That would be great because we need to setup the scheduled task and "forget" about it. We can't do that if we can't store the secret permanently.

**Comment by deawar** [comment]
We also need multiple Manufacturer's Warranty Info for assets currently deployed. Dell, HP, Lenovo, Apple would be the short list.
But also Meraki, Cisco and Datto for networking equipment.
